### ISSUE TITLE
Use of deprecated expl3 \prop_get:Nn function

### ISSUE THREAD

**Issue by fruchart** [loopspace/hobby#1]
Hi,

It seems that `pml3array.sty` (and therefore the hobby library in general) does not work with recent versions of `expl3`, due to the fact that `\prop_get:Nn` was [deprecated](http://article.gmane.org/gmane.comp.tex.latex.latex3/3357) and replaced by `\prop_item:Nn`; replacing all occurrences seems to fix the issue. Beware of not replacing e.g. `\prop_get:NnNTF` functions which I believe were not renamed.

Best,

**Comment by loopspace** [comment]
Thanks for letting me know - I wasn't aware of the depreciation.  I agree with the fix and have implemented it. (Not sure how one references a specific commit, but #c6efda12bb2ffc8f68e64515898957175e5c3653 is the fix)
