### ISSUE TITLE
can't use `tension` when hobby is loaded 

### ISSUE THREAD

**Issue by kpym** [loopspace/hobby#2]
In the following code if you uncommencement the hobby package, the tension become `.5` (or something closer). This looks like a side effect.

	\documentclass[tikz]{standalone}
	%\usetikzlibrary{hobby}
	\begin{document}
	    \begin{tikzpicture}
	        \draw[thick,red,smooth,tension=3] plot coordinates {(0,0) (0,1) (1,1) (1,0)};
	    \end{tikzpicture}
	\end{document} 

Without Hobby : 
    ![without Hobby](https://i.stack.imgur.com/Taxc5.png)
With Hobby : 
    ![with Hobby](https://i.stack.imgur.com/3D6hc.png)

**Comment by loopspace** [comment]
There is a `tension` key in the `hobby` package.  Clearly, it is overwriting an existing key so I'll have to scope it more carefully.  Thanks for spotting this.

**Comment by loopspace** [comment]
As a quick fix, put

~~~
\tikzoption{tension}{\pgfsetplottension{#1}}
~~~

after loading the hobby library.  This will restore the old behaviour.  In the hobby code, `tension` is an alias for setting both `tension in` and `tension out` together so it's possible to do without it.

**Comment by kpym** [comment]
👍 Thanks for the workaround !

**Comment by loopspace** [comment]
No problem.

I'll figure out a proper fix in time, just need to see if there's a way I can keep the `tension` key because the two different uses are in different places.  If all else fails, I'll just rename it since I shouldn't overwrite keys that TikZ defines.

**Comment by kpym** [comment]
Probably you can simply add in your `tension/.code` the `\pgfsetplottension{#1}`. On even better, in place of `tension/.code` you can use `tension/.append code`. In this way the tikz `tension` key will set the "plot tension" and the two "hobby tensions" at the same time.
