### ISSUE TITLE
Make a smaller documentation PDF

### ISSUE THREAD

**Issue by kpym** [loopspace/hobby#5]
If you compile the documentation with XeLaTex [it is now](https://github.com/kpym/hobby/releases/download/v2019.03.27/hobby_doc.pdf) around 134Kb. But when compiled with PDFLaTeX it is around 535Kb. 

Publishing smaller PDFs preserve the planet !

*About publishing:* as you changed in the documentation the main source to `https://github.org/loopspace/hobby`, probably it will be a good idea to : 

- use GitHub releases for simple downloads, like [I have done](https://github.com/kpym/hobby/releases) in the fork of this repo; 
-  add a `README.md` or simply push the `README.txt` generated by the `dtx` ;)

**Comment by loopspace** [comment]
The different size of PDF is strange.  Is there anything obvious causing that?

* Didn't know about releases, sounds like a good idea.  I'll look into that.
* Keep meaning to do that, but it's been a low priority as I expect most people get their code from CTAN.

**Comment by kpym** [comment]
No, it is not strange, there are reasons for this ([here](https://tex.stackexchange.com/q/38145) or [here](https://tex.stackexchange.com/q/54435) or ...). This (and the unicode support) is why I always use XeLaTeX if I can. 

GitHub releases are not an alternative but a complement to CTAN. The advantage to have GitHub releases in addition to CTAN is that : 

- the last version is available immediately;
- the user can get an old version very easily;
- if the user is on github it can grab the library without going to CTAN;
- you can provide the "expanded" version from the dtx as zip.
 
But I agree that this costs additional effort that have potentially only one client (me). 😃
